### PR TITLE
Signin page patch 1

### PR DESCRIPTION
**Pull request by megzehn**
Fixed spacing issue for "Exception"

### CODE REVIEW

**Comment by humancompanion-usds** [comment]
@megzehn - This is still in Draft status. If you mark it Ready for review then we can approve it if you are in fact done with your changes here.

**Comment by megzehn** [comment]
Done. Thank you, @humancompanion-usds!

**Review by humancompanion-usds — APPROVED** [review]

**Comment by megzehn** [comment]
@humancompanion-usds I'm not seeing these changes reflected on the live page. Could you double check this?

I'm just trying to put "**Exception**" on a separate line in the [style guide sign-in page](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification) under Considerations. 

Thank you!

**Comment by humancompanion-usds** [comment]
@megzehn - When someone approves your change it is still your responsibility to merge the change and thus deploy it. I can do that for you now but in future, just be aware that folks won't merge your changes for you.

**Comment by megzehn** [comment]
Hi @humancompanion-usds, I don't have write access to merge the change--even after someone approves the changes. 

Normally I would ask Beth Potts, but she was OOO. Is it possible to adjust my permissions so I can merge after a PR gets approved? Or is there someone else on your team I should ask in instances like this one?

**Comment by humancompanion-usds** [comment]
@megzehn - Ah! Now I follow. Okay, I gave you Maintainer access, the same as Beth. Give that a go for the next PR.

**Comment by megzehn** [comment]
Perfect! Thank you, @humancompanion-usds!

**Pull request merged**
