### PR TITLE
testing breaking build

### PR DESCRIPTION
**Pull request by mchelen-gov**

### CODE REVIEW

**Comment by Andrew565** [comment]
Are you requesting a broken dependency be merged into the main branch? Or should this be treated a draft PR, i.e. "Do Not Merge"?

**Review by Andrew565 — CHANGES_REQUESTED** [review]
Needs clarification.

**Comment by Andrew565** [comment]
@mchelen-gov Is this PR still needed?

**Comment by mchelen-gov** [comment]
> Are you requesting a broken dependency be merged into the main branch? Or should this be treated a draft PR, i.e. "Do Not Merge"?

@Andrew565 This PR intentionally creates a build breaking change, to validate the function of CI checks. It appears that all the checks pass even when the build is not functional?

**Comment by Andrew565** [comment]
Forgive me, but did you still want this PR merged in or no?

**Comment by jamigibbs** [comment]
Hi @mchelen-gov! 👋🏼  I know this PR is quite old but I was doing some cleanup and noticed it was still open. I merged in main and tested your build break again. It looks like it's "working" as expected now so I'm going to close this PR:

Screenshot 2024-11-04 at 11 30 06 AM

Screenshot 2024-11-04 at 11 32 38 AM


Please re-open if you'd like or let me know if there is some additional work you were wanting to validate.

**Pull request closed without merging**
