### PR TITLE
Update URL standards documentation

### PR DESCRIPTION
**Pull request by erinrwhite**
- moved URL standards out of content style guide and into components
- updated ALT text for diagram of URL
- added guidelines for parameters in URLs

Per [va.gov-team ticket #81192](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81192)

### CODE REVIEW

**Comment by erinrwhite** [comment]
Assigned @mnorthuis for review

**Review by humancompanion-usds — APPROVED** [review]

**Comment by humancompanion-usds** [comment]
There are coding guidelines relevant for front-end developers that you might want to include a pointer to from this doc: https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/blob/main/template-rendering/revproxy-vagov/vars/README.md

**Comment by mnorthuis** [comment]
Let's hold on linking to the developer redirect info, we are in the process of reworking that process and documentation, and don't currently reference redirects in this section quite yet.  Putting a pin in that for when we add that info here. 

This looks great @erinrwhite!

**Review by mnorthuis — APPROVED** [review]

**Comment by erinrwhite** [comment]
thank you @mnorthuis @humancompanion-usds for the review! Looks like this is ready to merge - can one of you do so? Thanks!

**Pull request merged**
