### PR TITLE
Updates to Hub guidance, adding mobile screenshots

### PR DESCRIPTION
**Pull request by erinrwhite**
Updated Hub guidance per @mnorthuis - 

- updated content per https://github.com/department-of-veterans-affairs/va.gov-team/issues/65451
- including mobile screenshot(s) broken down for each section of the page
- new desktop screenshot

### CODE REVIEW

**Comment by jamigibbs** [comment]
Hi @erinrwhite 👋🏼 I noticed that your preview is failing on this PR. I _think_ it's doing that because you are creating this PR from a fork of the repo instead of branching directly off of it and pushing directly. 

The error I'm seeing is related to not being able to get an AWS key which might be related to this PR coming from outside of the original repository.

Screenshot 2024-11-01 at 3 00 49 PM

I will do some testing to see if I can resolve it. Otherwise, you can continue on this PR without having a preview, or, you can create a new PR that just branches directly off of this repository.

**Comment by erinrwhite** [comment]
Thanks for troubleshooting this @jamigibbs and sorry for the trouble! Closing this PR and will branch off the main repo.

**Comment by erinrwhite** [comment]
@jamigibbs Ah, that's why I forked instead of branching - I don't have write access to this repo. That's for the best! 😂 [I have had PRs successfully merged before](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pulls?q=is%3Apr+is%3Aclosed+author%3Aerinrwhite+) but have been working on this change on my machine, on and off, for a couple weeks, so maybe that's part of the issue?

I can either start a brand new PR with a brand new fork in my repo, or reopen this PR. What do you recommend?

**Comment by erinrwhite** [comment]
@jamigibbs ooh I love this new feature! This will be really helpful. I'm going to use my new powers to branch the repo and submit a new PR. Thanks so much.

**Comment by erinrwhite** [comment]
New PR submitted - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3486

**Pull request closed without merging**
