### PR TITLE
Adding "contention" to content style guide word list

### PR DESCRIPTION
**Pull request by mengA6**
per [this slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1712076604005559?thread_ts=1712002651.162639&cid=C04KW0B46N5)

### CODE REVIEW

**Comment by bethpottsVADEPO** [comment]
@megzehn Would you please edit this entry to align with our style? Thanks!

**Comment by megzehn** [comment]
@mengA6 and @bethpottsVADEPO, I made some slight edits for consistency with our other entries. Does this work for you both?

> **contention**
> : Use "condition" or an alternate word or phrase instead, depending on context. Internally, "contention" refers to an issue connected with a claim. Typically this is a medical condition, but in some cases it could be for other things like claiming a dependent.

@mengA6 thank you for this suggestion!

**Review by bethpottsVADEPO — APPROVED** [review]
Looks good, thanks, Megan

**Comment by mengA6** [comment]
Looks good to me. Thank you!

**Comment by megzehn** [comment]
Hi @humancompanion-usds, could you or someone on your team help us merge this small addition to the Style guide word list? @bethpottsVADEPO approved it. 

cc @DanielleThierryUSDSVA for visibility. 

Let me know if there are any issues! Thank you!

**Review by humancompanion-usds — APPROVED** [review]

**Pull request merged**
