### PR TITLE
Update va-button docs

### PR DESCRIPTION
**Pull request by andresriveratoro**
This PR updates `component-library` dependency to v10.5.1. This version includes the component docs for va-button.

### CODE REVIEW

**Comment by andresriveratoro** [comment]
Updating the maturity scale for the button results in an incorrect maturity scale in the side navigation for sub-pages because it's inheriting the parent page maturity scale.

Screen Shot 2022-06-13 at 12 33 46

**Comment by andresriveratoro** [comment]
It seems this issue is affecting a few of our sub-page components. I'm going to create an issue for this work.

**Comment by andresriveratoro** [comment]
I've created the issue for fixing sidenav subpage component maturity scale [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/945).

**Comment by andresriveratoro** [comment]
In the meantime, I think it's less harmful to display the incorrect icon for Button pair than it is for va-button. `va-button` is currently `use with caution: candidate` while Button pair is `use: deployed`.

**Review by k80bowman — APPROVED** [review]

**Pull request merged**
