### PR TITLE
Add description to search results

### PR DESCRIPTION
**Pull request by andresriveratoro**
## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/776

### CODE REVIEW

**Comment by andresriveratoro** [comment]
@humancompanion-usds 

Here's how it looks using h2s for titles and some additional styling to match VA.gov.

Screen Shot 2022-06-16 at 13 02 01

**Comment by humancompanion-usds** [comment]
@andresriveratoro - That looks great! Just a small change to make given that I [just wrote guidance around this](https://design.va.gov/components/card#when-to-use-caution), let's just make one large content area with a white background for the results to all sit in rather than each result in a card. I think the Card approach here creates visual noise we don't need. As long as we have the spacing right (12px margin on top, 32px margin on bottom) for each block of the results we should be fine. The typography will do the heavy lifting here. Thanks!!

**Comment by andresriveratoro** [comment]
@humancompanion-usds How about this?

Screen Shot 2022-06-16 at 16 33 19

**Review by humancompanion-usds — APPROVED** [review]
Awesome! Thanks.

**Pull request merged**
