### PR TITLE
Adding Vets.gov word list entries to VA.gov style guide

### PR DESCRIPTION
**Pull request by KevinMHoffmanUSDS**
This is still a WIP but some entries have been added.

### CODE REVIEW

**Comment by KevinMHoffmanUSDS** [comment]
@RLHecht @jenniferlee-dsva This should be a fully restored PR (thanks @batemapf). Let me know if this gets you back on track, and apologies again for jumping the gun!

**Comment by pdavies88** [comment]
@KevinMHoffmanUSDS @RLHecht we are trying to clean up some of these old PRs. Are these changes still needed to this file and should they be merged in?

**Comment by pdavies88** [comment]
@KevinMHoffmanUSDS @RLHecht we are trying to clean up some of these old PRs. Are these changes still needed to this file and should they be merged in?

**Comment by KevinMHoffmanUSDS** [comment]
Good morning! This is an old PR; @DanielleThierryUSDSVA and @bethpotts would be the folks that would have the final say on if the content is accurate. CC @humancompanion-usds @pdavies88

**Review by bethpottsVADEPO — APPROVED** [review]

**Review by pdavies88 — APPROVED** [review]

**Pull request merged**
