### PR TITLE
Edits to style guide

### PR DESCRIPTION
**Pull request by megzehn**
Hello! I made some tweaks to the style guide. @bethpotts or @DanielleThierryUSDSVA, do you mind taking a look when you have a chance? Thank you so much! 

___________________

A quick summary of my changes: 

**Word list**

Added these entries per ticket [#19437](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19437#event-7733909463):
- Defense Department
- Department of Defense
- PACT Act 
- Edith Nourse Rogers STEM Scholarship
- Service-connected disability rating

Changed styling to make entries more prominent per ticket [#54325](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/54325)

**Bulleted lists** 

Revised guidelines to recommend introducing lists with a full sentence per ticket [#19437](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19437#event-7733909463)

**Dates and numbers**

 Revised guidelines to recommend against en dashes per ticket [#19437](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19437#event-7733909463) and [Slack thread here](https://dsva.slack.com/archives/C03MP8MEPCN/p1657747535451789) and [also here](https://dsva.slack.com/archives/C8E985R32/p1657561939162259)

**Punctuation** 

 Revised guidelines to recommend against en dashes

**Addresses**  

Removed duplicate text 

**Health content** 

Added missing line break in example

### CODE REVIEW

**Comment by bethpottsVADEPO** [comment]
For the Board of Veterans' Appeals entry, would you put "Veterans" in quote marks without the apostrophe? And add this at the end: Veterans'.
Like this:
Note that "Veterans" is plural with a plural possessive: Veterans'

**Comment by bethpottsVADEPO** [comment]
@megzehn We need to remove this entry as it is incorrectly referencing Chapter 36 instead of Chapter 31. And for Ch. 31, we're now leaning toward saying, "professional and vocational counseling."

**educational and vocational counseling**
: We use this style of phrasing to be consistent with VR&E Chapter 36: Educational and Vocational Counseling.

Also, please change the preceding entry that mentions Chapter 36 to "Educational and **Career** Counseling."
Thanks!

**Comment by bethpottsVADEPO** [comment]
@megzehn Can you make these entries match (with "it should be bolded") and cap "Exception"? Also, add to the end of each: Use a colon following "Note." / Use a colon following "Exception."

**Note**
: Used to call special attention to something. It is bolded and never in all caps.

**exception**
: Used to call special attention to something. It should be bolded and never in all caps.

-----------------------------

For this entry, please put quote marks around "post-9/11" in the last sentence, like this:

**post-9/11** - add quote marks around "post-9/11"
: Hyphenate. We use the slash rather than the hyphen for 9/11 (not 9-11). Example: Post-9/11 GI Bill. In cases when "post-9/11' stands alone rather than as part of a program name, it should be lowercase.

**Comment by megzehn** [comment]
Thanks for reviewing, @bethpottsVADEPO! 

I removed the "educational and vocational counseling" entry and modified "educational and career counseling," so it's like this: 

educational and career counseling : We use this style of phrasing to be consistent with VR&E Chapter 36: Educational and Career Counseling. Note: This style differs from the style within eBenefits VR&E > Education and Career Counseling pages.

Do you want to have an entry in the word list for Chapter 31? Under "professional and vocational counseling"? Let me know, and I can add something in. Your other changes should be reflected in this PR as well. 

_________________________

@humancompanion-usds, do you mind reviewing the word list entries in this PR and make sure they look OK in preview? I followed your example in the "Payments and debts" section of the style guide. 

Thank you!!

**Comment by bethpottsVADEPO** [comment]
Thanks, @megzehn -- all looks good. Go forth! And thanks so much.

**Review by humancompanion-usds — APPROVED** [review]

**Pull request merged**
