### PR TITLE
Adding we, us, you text

### PR DESCRIPTION
**Pull request by jenniferlee-dsva**
@jaredcunha-usds - just checking if I used your table html snippet correctly. Does it look ok?

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva  Looks good to me. If you want in the future, you can even add some context to the boxes as well. 

Screen Shot 2019-03-27 at 6 17 13 PM

I'll merge this in tomorrow so this message doesn't disappear on you and you don't see my reply.

**Comment by jenniferlee-dsva** [comment]
Great suggestion - hard to tell without seeing it closer to what it actually looks like. 

Please remove the quotation marks around the example though. And then it's perfect!

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva I just did the example in the browser, I didn't update the code. If you'd like, you can update this pull request to incorporate or leave as is for now. Update later too. Up to you.

**Comment by jenniferlee-dsva** [comment]
ah, now I get it. okay. let me try...

**Pull request merged**
