### PR TITLE
Update horizontal-rules.md

### PR DESCRIPTION
**Pull request by GnatalieH**

### CODE REVIEW

**Comment by GnatalieH** [comment]
[Slack conversation approval](https://dsva.slack.com/archives/GTV1Z9FQX/p1642791508025000) from DSC for name change and added guidance.

**Comment by GnatalieH** [comment]
@k80bowman I haven't forgotten about this PR, I'm just still on the fence about the rename. The OCD librarian in me doesn't like the thought of having a mismatching class name. The main point of the PR was to add guidance, so I'm thinking we should leave the name the same for now.

**Comment by k80bowman** [comment]
@GnatalieH take your time. I'll ask a couple of folks about this and get their opinions on the name change. This ticket isn't technically in the current sprint anyway, so no rush.

**Comment by humancompanion-usds** [comment]
I pulled this in with my changes in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/708 Horizontal rules are now Divider

**Pull request closed without merging**
