### PR TITLE
Adding Fourth Mission to word list

### PR DESCRIPTION
**Pull request by RLHecht**
Added term Fourth Mission to word list section.

### CODE REVIEW

**Comment by RLHecht** [comment]
@jenniferlee-dsva Peggy and I did our parts on the style guide. This is ready to be reviewed and merged. I can then also add an update to the What's New section.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I also updated the what's new section. We can change the date for when we are publishing. I have it set now for September 10. This is ready to be reviewed and merged if all good.

**Comment by jenniferlee-dsva** [comment]
Looks good to me @RLHecht - feel free to merge whenever you're ready.

**Comment by jenniferlee-dsva** [comment]
Just merged - I see your comment to merge if all good.

**Review by jenniferlee-dsva — COMMENTED** [review]
Looks okay to me! No changes.

**Pull request merged**
