### PR TITLE
Create expandable-alert.md

### PR DESCRIPTION
**Pull request by lildziner**
@sshein here's a first pass at the expandable alert. The [code snippet from a live Vet Center page](https://www.va.gov/springfield-ma-vet-center/) isn't working for me.

### CODE REVIEW

**Comment by sshein** [comment]
cool :) maybe @cvalarida can help with the code? you can always ping him on slack too. also someone told me Riley's team coded this in somewhere sharable, is that the case? (maybe ping Justin or Riley and ask?)

**Comment by bkjohnson** [comment]
I did some digging and it looks like you're not seeing what you expect because `vets-website` has a script that is identifying that element and applying some additional transformations on it:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/facilities/vet-center/createExpandableOperatingStatus.jsx

**Comment by cvalarida** [comment]
@bkjohnson What can we do to make this work here?

**Comment by lildziner** [comment]
@LinnJS I heard you have a better working example of the expandable alert on the debt portal. Is that something that you can point us to?

**Comment by bkjohnson** [comment]
We might be able to extract the specific `static-pages` files, compile them down using webpack, and include that script bundle on this page.

Another option would be to rewrite it in a way that avoids React - either like we have done in `formation` or with a web component.

**Comment by sshein** [comment]
if it seems too complicated, can we just include a screenshot of the component open and closed, and then a link out to wherever folks can find the code?

**Comment by lildziner** [comment]
I don't think I have write access to on this repo to merge the pull request. I tried approving first but it won' let me do that either. Am I missing something obvious?
[screenshot of GH telling me I can't approve my own PR]

**Comment by bkjohnson** [comment]
It won't let you approve it since you're the author.

I took a look at the settings and the `design.va.gov-writers` group has "write" permissions, meaning they should be able to merge PRs. @sshein is a maintainer of that group, so she should be able to give you access which will give you the permissions you need.

**Comment by sshein** [comment]
ah ok, I can also just merge for you Leyda for now. Is it ready to be merged?

**Comment by lildziner** [comment]
Yes, please @sshein can we try. We can refine from there?

**Comment by sshein** [comment]
ok I merged it should be up in a bit, keep a look out :) https://design.va.gov/experimental-design/

**Comment by sshein** [comment]
looks like it's up @lildziner! But yeah the code example isn't working. I'd recommend just linking to where folks can find the code if that's possible? Also are there any accessibility considerations or anything else that needs to be laid out on this page? https://design.va.gov/experimental-design/expandable-alert

**Pull request merged**
