### PR TITLE
WIP - allow docker container to reach github ssl (SSL inappropriate fallback)

### PR DESCRIPTION
**Pull request by omgitsbillryan**
Problem ([source build](http://jenkins.vetsgov-internal/job/testing/job/vets-design-system-documentation/job/vaec-migration/2/console)):
```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-64_binding.node": 

write EPROTO 139989193935720:error:1425F175:SSL routines:ssl_choose_client_version:inappropriate fallback:ssl/statem/statem_lib.c:1944:
```

Copies the necessary VA certificates required for SSL communication through the TIC.

### CODE REVIEW

**Comment by omgitsbillryan** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/298Connects:

**Comment by omgitsbillryan** [comment]
Some findings:
- docker image gets built and installs certificates successfully (i think):
```
Step 4/6 : RUN update-ca-certificates
 ---> Running in 8271422b505e
[91mWARNING: ca-cert-dod-eca.pem does not contain exactly one certificate or CRL: skipping
[0m[91mWARNING: ca-cert-va.pem does not contain exactly one certificate or CRL: skipping
[0m[91mWARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```
- I can reproduce the error by running a bash shell inside the docker image: 
`wget https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-64_binding.node`
  - also inside the docker image: `openssl s_client -showcerts -connect github.com:443` succeeds - i thought `wget` was based on the system `openssl` install 🤷‍♂ 
- `method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object` was added to http://jenkins.vetsgov-internal/scriptApproval/ to allow `docker.build()` inside the `jenkinsfile`

**Comment by jaredcunha-usds** [comment]
@omgitsbillryan - Just following up on this since there hasn't been much activity lately. Should this PR remain open?

**Comment by omgitsbillryan** [comment]
This problem is not unique to VDSD. A generic solution is being developed that should be applicable here once it's done. Wyatt Walter or Nathan Dister probably have more details.

**Pull request closed without merging**
