### PR TITLE
Run build on pull request

### PR DESCRIPTION
**Pull request by mchelen-gov**

### CODE REVIEW

**Review by Andrew565 — CHANGES_REQUESTED** [review]
Scheduling a meeting with mchelen to discuss this proposed change.

**Comment by Andrew565** [comment]
@mchelen-gov Is this PR still needed?

**Comment by mchelen-gov** [comment]
> @mchelen-gov Is this PR still needed?

@Andrew565 Are any other build checks currently being performed on PRs?

**Comment by Andrew565** [comment]
> > @mchelen-gov Is this PR still needed?
> 
> @Andrew565 Are any other build checks currently being performed on PRs?

No, currently the only build is being done when code is pushed to main as part of a deploy script.

**Review by Andrew565 — APPROVED** [review]

**Pull request merged**
