### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by taylojill**
@GnatalieH and @humancompanion-usds Adding images for the new Keep a record of submitted information pattern.

### CODE REVIEW

**Comment by GnatalieH** [comment]
@humancompanion-usds Jill needs to have a folder for keep-a-record-of-submitted-information created for these images. Neither she nor I are able to create new folders in the images/patterns/help-users-to/ directory. Thanks. CC @taylojill

**Review by GnatalieH — COMMENTED** [review]
@taylojill the images look good. I'd just remove the spaces from the file names like we discussed, but otherwise I think they're good.

**Comment by humancompanion-usds** [comment]
There does seem to be a way to create a folder in the web interface: https://github.com/orgs/community/discussions/22534 But if you want to approve and merge, just ping me after and I can create a new folder and move them.

**Comment by taylojill** [comment]
Thanks Matt! I'll give it a try. cc @GnatalieH

**Review by GnatalieH — APPROVED** [review]
Approved @taylojill.

**Review by GnatalieH — APPROVED** [review]

**Pull request merged**
