### PR TITLE
WIP: create outline of patterns

### PR DESCRIPTION
**Pull request by jaredcunha-usds**
This is a work in progress of some of the pattern documentation we captured.

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
@rtwell @goldenmeanie @lalexanderson-dsva @smoonpeyes Here's a pull request i'll keep open as we work through the pattern documentation

**Comment by jaredcunha-usds** [comment]
So, for the patterns section, the new items, which have stars next to them, . 

Screen Shot 2019-05-09 at 10 08 46 AM

**Comment by jaredcunha-usds** [comment]
Screen Shot 2019-05-09 at 11 10 52 AM

Can't really show what the full nav looks like, so here it is:
```
- Overview
-  Authenticated / Unauthenticated
         - Sign-in prompt
- Benefit applications
         -  Eligibilty
         - How to apply
         - Apply now
         - After you apply
         - Waivers
- Content presentation (no work completed here)
         - Information callouts 
         - Expandable content
- Disabled content
         - Default
         - Read-only
         - Hidden
- Form feedback
         - Error messages
- Forms
         - Pre-filled data
         - List and loop
         - Chapter sequences
         - Double entry
         - Upload documentation
         - Progressive disclosure
         - Tooltips
         - Writing questions
         - Simple templates
- Hub pages
- Masking numbers
- Wizard
```

**Comment by artsymartha68** [comment]
Closing this with Jared's blessing.

**Pull request closed without merging**
